kind: pipeline
name: default

steps:
- name: test4
  image: golang
  commands:
  - go test ./...
  - go build ./...
- name: detach4
  image: golang
  commands:
  - go test ./...
  detach: true
- name: depends_on4
  image: golang
  commands:
  - go test ./...
  depends_on:
  - detach4
